import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from "next/font/google"
import Providers from "@/components/Providers";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className}`}
      >
        <Providers>
          <ToastContainer
            position="top-center"
            autoClose={3000}
            draggable
            closeOnClick
            theme="colored"
          />
          {children}
        </Providers>
      </body>
    </html>
  );
}
